name: Ruby Gem

on:
  push:
    branches:
      - main
    paths:
      - lib/turnstiled/version.rb

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read VERSION
        id: version
        run: echo "version=$(rake version)" >> $GITHUB_OUTPUT

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          bundler-cache: true
          version: ruby

      - name: Create GitHub Release
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createRelease({
              name: 'Release ${{ steps.version.outputs.version }}',
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "v${{ steps.version.outputs.version }}",
              target_commitish: context.sha,
              generate_release_notes: true,
            })


      - uses: rubygems/release-gem@v1
